** rise of republican party
- Convinced Northerners that the "slave power" posed immediate threat to liberty
  - Slavery creates strict system of hierarchy
  - Threatened the American Dream
  - Free labor could not compete with slave labor; slavery's expansion must be halted to ensure freedom for the white laborer
- Not abolitionists per se; just wanted to prevent the spread of slavery

*** northern economy
- 1850s: Northern stays acquiring large amount of guap/skrilla
- Increased the amount of investment/building of railroads connecting the midwest to North
  - Forming new cultural connections between Northern businessmen and Midwest farmers
- Economic integration between Northwest and Northeast creates groundwork for unification in the republican party

** bleeding Kansas
- 1854 elections in Kansas corrupted by Missourians
  - resulted in pro-slavery territory legislation
  - supported by Franklin Pierce
  - Anti-slavery territory governor removed
- Civil war breaks out within Kansas
  - 200 killed
  - tons of property/infrastructure damage
  - Charles Sumner
- Kansas admittance put on hold

** Dred Scott v. Sandford
- Dred Scott (current slave living in free territory) sues for his freedom
- SCOTUS determines that Congress possessed no power under the Constitution to bar slavery from a territory
  - Reinforces ideas of white citizenship
  - Scott still a slave despite living in free territory (but given immediate Emancipation!)
- Effectively declared Republican platform as unconstitutional
- President Buchanan declared that slavery, henceforth existed in all the territories, "by virtue of the Constitution"

[[https://tinyurl.com/jkozbyp][Link To Case]

** Rise of Lincoln
 - Stephen Douglas runs for Senate re-election
 - Faces unexpectedly strong challenge from Abraham Lincoln
 - Developed critique of slavery that became central to Republican platform
   - Not completely abolitionist; willing to negotiate with South
   - Echoed sentiments that blacks were not necessarily equal to whites; but that all deserved a chance at the American dream

"I hate it because of the monstrous injustice of slavery itself. I hate it because it deprives our republican example of its just influence in the world -- enables the enemies of free insitutions, with plausibility, to taunt us as hypocrites -- causes the real friends of freedom to doubt our sincerity." ---Abraham Lincoln

** Lincoln-Douglas debates
 - The Lincoln-Douglas debates more popular than Yeezus tour
 - To Lincoln, freedom = opposition of slavery
   - June 1858 Lincoln gives House Divided speech: "A house divided against itself

** John Brown
 - Very devout Old Testament Christian
 - Aided abolitionist war effort in Bleeding Kansas, midwest, and Canada
 - October 16, 1859, Brown and 21 men seize military arsenal at Harpers Ferry, VA
 - Captured, tried, and convicted of Treason
   - Demeanor during trial won over many Northerners
 - Violent uprising increased sectional tensions between North and South

** southern nationalism/Fire Eaters
 - 1850s Southerners argue that they would be better off outside the Union
   - Price of slaves making it impossible for white to attain American Dream
   - North reaped benefits of slavery; while southerners becoming bankrupt
 - Southerners strengthen bonds of slave
   - "Slavery is our king. Slavery is our truth. Slavery is our divine right."
 - Southerners more bold in talking publically of slave-based expansion
   - Ostend Manifesto: buying/capture of Cuba
   - Tennessean William Walker tries to take over several Latin American territories
 - By early 1860, seven Deep South states demanded Democratic Platform pledge to protect slavery in all new territories

** election of 1860
 - Election pure chaos
   - North: Lincoln vs. Douglas
   - South: Douglas vs. Breckinridge vs. John Bell (no republican candidate)
 - Returns most sectional in nation's history
 - Douglas carried support in most of the nation, but not enough to win
 - Lincoln fails to win majority of popular vote (only 40%), but carries North and electoral college
 - Without a single voite in ten Southern states, Lincoln was elected the nation's sixteenth president

** secession crisis
 - Most knew Lincoln would not attempt immediate abolition; but his election marked start of potential long rule of Republicans
 - South Carolina first state to secede
   - 6 other states follow (all Cotton Kingdom: TX, LA, AL, MS, FL, GA)
 - December 20, 1860, the legislature unanimously voted to leave the Union
   - Declaration of the Immediate Causes of Secession placed the issue of slavery at the center of the crisis
 - Buchanan lame duck,

Crittenden Proposal

 - Extend Missouri Compromise line to Pacific
 - Protect institution of slavery in slave states
 - Wildly popular in Congress
 - Lincoln not a plan; plan dies

** and the war came

*** Fort Sumter
 - As states seceded, they began seizing U.S. government property (post offices, court-houses, and forts)
 - By March 4, only 2 forts remained in federal hands
 - Fort Sumter (Charleston SC) most important
   - Surrounded by confederates; cut off supplies
 - Lincoln first day: received word that Sumter running low on supplies
   - Could not wait for dust to se
